jobs:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd BotApi/app
      install:
        - pip install -r BotApi/app/requirements.txt
      script:
        - python3 -m pytest -v tests/test.py

    - language: java
      jdk:
        - openjdk11
      os: linux
      dist: xenial
      before_install:
        - wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
        - unzip -qq gradle-7.0.2-bin.zip
        - export GRADLE_HOME=$PWD/gradle-7.0.2
        - export PATH=$GRADLE_HOME/bin:$PATH
      before_script:
        - cd Service/
      script:
        - gradle build -x test

notifications:
  email:
    - gorskovdmitry@gmail.com
